services:
  - type: web
    name: client
    env: node
    rootDirectory: client
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    runtime: node 18