services:
  - type: web
    name: client
    env: node
    buildCommand: yarn cache clean && yarn install && yarn build
    startCommand: yarn preview
    envVars:
      - key: NODE_ENV
        value: production
    runtime: node 18
