services:
  - type: web
    name: flare48-client
    env: static
    staticPublishPath: client/build
    buildCommand: npm install && npm run build --prefix client
    startCommand: npm start --prefix client
