services:
  - type: web
    name: client
    env: static
    buildCommand: yarn install && yarn build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
    runtime: node 18
