services:
  - type: web
    name: flare48-client
    env: static
    rootDir: client
    staticPublishPath: build
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
