services:
  - name: flare48-client
    type: web  # Ensure this is a web service type
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start  # Ensure to start the preview server after building
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://flare48-2sfl.onrender.com  # Updated API URL
