services:
  - type: web
    name: flare48-client
    env: static
    rootDir: client
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    startCommand: npm run preview
  - type: web
    name: flare48-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000