services:

  - name: flare48-client
    type: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://flare48-server.onrender.com 
