name: Server CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server  # Ensure all commands run inside the server folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint (if configured)
        run: npm run lint || echo "No lint script found, skipping."

      - name: Run Tests (if any)
        run: npm test || echo "No tests found, skipping."